apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: app-db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-db
  template:
    metadata:
      labels:
        app: app-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "supersecretpassword"
            - name: MYSQL_DATABASE
              value: "app_db"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc