apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs20-sparta-app-deployment
  namespace: default
  labels:
    app: nodejs20-sparta-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs20-sparta-app
  template:
    metadata:
      labels:
        app: nodejs20-sparta-app
    spec:
      containers:
      - name: sparta-node-app
        image: vrangrops/sparta-test-app:latest
        ports:
        - containerPort: 3000
        command: ["/bin/sh"]
        args: ["-c", "node seeds/seed.js; node index.js"]
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/tictactoe"
        - name: STATEFUL_MODE
          value: "mongodb"