apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-minikube-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-minikube
  template:
    metadata:
      labels:
        app: hello-minikube
    spec:
      containers:
      - name: hello-minikube
        image: registry.k8s.io/e2e-test-images/agnhost:2.39
        args:
        - netexec
        - --http-port=8080
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-minikube-service
spec:
  type: LoadBalancer
  selector:
    app: hello-minikube
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
