version: "3"
#services = container
# docker compose creates both containers in the smae network
services:
  redis-server:
    image: 'redis'
  node-app:
    restart: always
    build: .
    ports:
      - "4001:8081"